version: '2'


services:


  nginx_data:
    image: tianon/true
    volumes:
      - ./../data/proxy/conf.d/:/etc/nginx/conf.d/
      - ./../data/proxy/vhost.d/:/etc/nginx/vhost.d/
      - ./../data/proxy/html/:/usr/share/nginx/html/
      - ./../data/proxy/certs/:/etc/nginx/certs/
      - ./config/nginx/htpasswd/:/etc/nginx/htpasswd/:ro


  log_data:
    image: tianon/true
    volumes:
      - ./../log/nginx-proxy/:/var/log/nginx/


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - nginx_data
      - log_data


  dockergen:
    image: jwilder/docker-gen
    container_name: dockergen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    volumes_from:
      - nginx_data
    environment:
      - DEFAULT_HOST=example.com


  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx_data
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=dockergen


  logrotate:
    image: blacklabelops/logrotate:latest
    volumes_from:
      - log_data
    environment:
      - LOGS_DIRECTORIES=/var/log/nginx/
      - LOGROTATE_INTERVAL=daily
      - LOGROTATE_COPIES=60
      - LOGROTATE_SIZE=10M
      - LOGROTATE_PARAMETERS=v
      - LOGROTATE_CRONSCHEDULE=0 0 * * * *